globalThis.window = globalThis.window || {};
(() => {
  const SHAPES={I:[[1,1,1,1]],J:[[1,0,0],[1,1,1]],L:[[0,0,1],[1,1,1]],O:[[1,1],[1,1]],S:[[0,1,1],[1,1,0]],T:[[0,1,0],[1,1,1]],Z:[[1,1,0],[0,1,1]]};
  const COLORS={I:'#28c6f7',J:'#5571ff',L:'#ff9f43',O:'#ffe14d',S:'#4dd68a',T:'#b76cff',Z:'#ff5d73'};
  const clone=value=>JSON.parse(JSON.stringify(value));

  class Engine {
    constructor(random=Math.random){this.random=random;this.cols=10;this.rows=20;this.reset()}
    reset(){this.board=Array.from({length:this.rows},()=>Array(this.cols).fill(0));this.score=0;this.lines=0;this.level=1;this.paused=false;this.over=false;this.lastCleared=0;this.bag=[];this.next=this.createPiece();this.spawn()}
    createPiece(){if(!this.bag.length)this.bag=Object.keys(SHAPES).sort(()=>this.random()-.5);const type=this.bag.pop();return{type,matrix:clone(SHAPES[type]),x:0,y:0}}
    spawn(){this.current=this.next;this.next=this.createPiece();this.current.x=Math.floor((this.cols-this.current.matrix[0].length)/2);this.current.y=0;if(this.collides(this.current.matrix,this.current.x,this.current.y))this.over=true}
    collides(matrix,x,y){return matrix.some((row,dy)=>row.some((cell,dx)=>cell&&(x+dx<0||x+dx>=this.cols||y+dy>=this.rows||(y+dy>=0&&this.board[y+dy][x+dx]))))}
    move(dx,dy){if(this.paused||this.over||this.collides(this.current.matrix,this.current.x+dx,this.current.y+dy))return false;this.current.x+=dx;this.current.y+=dy;return true}
    rotate(){if(this.paused||this.over)return false;const matrix=this.current.matrix[0].map((_,i)=>this.current.matrix.map(row=>row[i]).reverse());for(const kick of[0,-1,1,-2,2])if(!this.collides(matrix,this.current.x+kick,this.current.y)){this.current.matrix=matrix;this.current.x+=kick;return true}return false}
    softDrop(){if(this.move(0,1)){this.score++;return true}this.lock();return false}
    hardDrop(){if(this.paused||this.over)return 0;let distance=0;while(this.move(0,1))distance++;this.score+=distance*2;this.lock();return distance}
    tick(){if(!this.paused&&!this.over)this.softDrop()}
    lock(){this.current.matrix.forEach((row,y)=>row.forEach((cell,x)=>{if(cell&&this.current.y+y>=0)this.board[this.current.y+y][this.current.x+x]=this.current.type}));this.clearLines();this.spawn()}
    clearLines(){let count=0;this.board=this.board.filter(row=>{if(row.every(Boolean)){count++;return false}return true});while(this.board.length<this.rows)this.board.unshift(Array(this.cols).fill(0));this.lastCleared=count;if(count){this.score+=[0,100,300,500,800][count]*this.level;this.lines+=count;this.level=1+Math.floor(this.lines/10)}return count}
  }

  class AudioFX {
    constructor(){this.enabled=localStorage.getItem('tetris-sound')!=='off';this.context=null}
    toggle(){this.enabled=!this.enabled;localStorage.setItem('tetris-sound',this.enabled?'on':'off');return this.enabled}
    tone(frequency,duration=.05,type='square',gain=.025,delay=0){if(!this.enabled)return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;this.context??=new AudioContext();const start=this.context.currentTime+delay,osc=this.context.createOscillator(),volume=this.context.createGain();osc.type=type;osc.frequency.setValueAtTime(frequency,start);volume.gain.setValueAtTime(gain,start);volume.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(volume).connect(this.context.destination);osc.start(start);osc.stop(start+duration)}
    play(name,value=1){if(name==='move')this.tone(150,.025);if(name==='rotate')this.tone(260,.045);if(name==='drop')this.tone(95,.08,'square',.04);if(name==='start'){this.tone(220,.06);this.tone(330,.08,'square',.03,.06)}if(name==='pause')this.tone(180,.08,'sine');if(name==='clear')for(let i=0;i<value;i++)this.tone(420+i*90,.12,'triangle',.045,i*.05);if(name==='over'){this.tone(220,.16,'sawtooth',.035);this.tone(110,.3,'sawtooth',.035,.15)}}
  }

  class App {
    constructor(){this.canvas=document.querySelector('#board');this.nextCanvas=document.querySelector('#next-board');this.gameOver=document.querySelector('#game-over');this.finalScore=document.querySelector('#final-score');this.pauseButton=document.querySelector('[data-a="pause"]');this.ctx=this.canvas.getContext('2d');this.nextCtx=this.nextCanvas.getContext('2d');this.engine=new Engine();this.audio=new AudioFX();this.timer=0;this.high=+localStorage.getItem('tetris-high-score')||0;this.touch=null;this.wasOver=false;this.bind();this.render()}
    bind(){document.querySelectorAll('[data-a]').forEach(button=>button.addEventListener('click',()=>this.action(button.dataset.a)));document.addEventListener('keydown',event=>this.key(event));this.canvas.addEventListener('touchstart',event=>{event.preventDefault();const t=event.changedTouches[0];this.touch=[t.clientX,t.clientY]},{passive:false});this.canvas.addEventListener('touchmove',event=>event.preventDefault(),{passive:false});this.canvas.addEventListener('touchend',event=>{event.preventDefault();if(!this.touch||!this.timer)return;const t=event.changedTouches[0],dx=t.clientX-this.touch[0],dy=t.clientY-this.touch[1];this.touch=null;this.action(Math.abs(dx)<18&&Math.abs(dy)<18?'rotate':Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>80?'drop':'down')},{passive:false})}
    action(action){if(action==='sound'){this.audio.toggle();this.render();return}if(action==='start'||action==='restart'){this.engine.reset();this.wasOver=false;this.startLoop();this.audio.play('start')}else if(action==='pause'&&!this.engine.over){this.engine.paused=!this.engine.paused;this.audio.play('pause')}else if(this.timer&&!this.engine.paused&&!this.engine.over){let success=false;if(action==='left')success=this.engine.move(-1,0);if(action==='right')success=this.engine.move(1,0);if(action==='down')success=this.engine.softDrop();if(action==='rotate')success=this.engine.rotate();if(action==='drop'){this.engine.hardDrop();success=true}if(success)this.audio.play(action==='rotate'?'rotate':action==='drop'?'drop':'move')}this.finishFrame()}
    key(event){const action={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowdown:'down',s:'down',arrowup:'rotate',w:'rotate',' ':'drop',p:'pause',escape:'pause',r:'restart'}[event.key.toLowerCase()];if(action&&(this.timer||action==='restart')){event.preventDefault();if(!event.repeat||['left','right','down'].includes(action))this.action(action)}}
    startLoop(){clearInterval(this.timer);this.timer=setInterval(()=>{this.engine.tick();this.finishFrame()},Math.max(120,800-(this.engine.level-1)*60))}
    finishFrame(){if(this.engine.lastCleared){this.audio.play('clear',this.engine.lastCleared);this.engine.lastCleared=0}if(this.engine.score>this.high){this.high=this.engine.score;try{localStorage.setItem('tetris-high-score',this.high)}catch(_){}}if(this.engine.over&&this.timer){clearInterval(this.timer);this.timer=0;if(!this.wasOver)this.audio.play('over');this.wasOver=true}this.render()}
    drawPiece(ctx,matrix,x,y,type,cell){matrix.forEach((row,dy)=>row.forEach((value,dx)=>{if(!value)return;ctx.fillStyle=COLORS[type];ctx.fillRect((x+dx)*cell+1,(y+dy)*cell+1,cell-2,cell-2);ctx.fillStyle='#ffffff35';ctx.fillRect((x+dx)*cell+3,(y+dy)*cell+3,cell-6,3)}))}
    renderNext(){const {matrix,type}=this.engine.next,cell=24,width=matrix[0].length*cell,height=matrix.length*cell;this.nextCtx.fillStyle='#0b1020';this.nextCtx.fillRect(0,0,160,120);this.drawPiece(this.nextCtx,matrix,(160-width)/(2*cell),(120-height)/(2*cell),type,cell)}
    render(){const cell=30;this.ctx.fillStyle='#090d1c';this.ctx.fillRect(0,0,300,600);this.ctx.strokeStyle='#19213a';for(let x=0;x<=10;x++){this.ctx.beginPath();this.ctx.moveTo(x*cell,0);this.ctx.lineTo(x*cell,600);this.ctx.stroke()}for(let y=0;y<=20;y++){this.ctx.beginPath();this.ctx.moveTo(0,y*cell);this.ctx.lineTo(300,y*cell);this.ctx.stroke()}this.engine.board.forEach((row,y)=>row.forEach((type,x)=>type&&this.drawPiece(this.ctx,[[1]],x,y,type,cell)));if(!this.engine.over)this.drawPiece(this.ctx,this.engine.current.matrix,this.engine.current.x,this.engine.current.y,this.engine.current.type,cell);this.renderNext();['score','high','lines','level'].forEach(id=>document.querySelector('#'+id).textContent=id==='high'?this.high:this.engine[id]);const sound=document.querySelector('#sound-toggle');sound.textContent=this.audio.enabled?'Sound On':'Sound Off';sound.setAttribute('aria-pressed',String(this.audio.enabled));this.pauseButton.textContent=this.engine.paused?'Resume':'Pause';this.pauseButton.setAttribute('aria-pressed',String(this.engine.paused));this.gameOver.hidden=!this.engine.over;this.gameOver.setAttribute('aria-hidden',String(!this.engine.over));this.finalScore.textContent=this.engine.score;document.querySelector('#status').textContent=this.engine.over?'게임 종료 — Restart를 누르세요.':this.engine.paused?'일시정지됨':this.timer?'플레이 중':'Start를 눌러 게임을 시작하세요.'}
  }
  let app;window.TetrisApp={initialize:()=>app||(app=new App)};window.TetrisEngine=Engine;if(typeof module!=='undefined')module.exports={Engine};
})();